Add glib to run deps
conda-forge/harfbuzz-feedstock pull request #57
Opened 2020-10-22 21:50 UTC by Tobias-Fischer

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

As indicated in the pkg-config file, glib is required when running harfbuzz and should thus be listed in the run dependencies.
```
Requires.private: freetype2, graphite2, glib-2.0
```
I found this bug when trying to compile opencv on aarch, where:

```
-- Checking for module 'harfbuzz'
--   Package 'glib-2.0', required by 'harfbuzz', not found
```

When pulling in glib manually, harfbuzz is found correctly.

2020-10-22 21:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-10-22 21:51 UTC, Tobias-Fischer commented
@conda-forge-admin, please rerender

2020-10-22 21:51 UTC, Tobias-Fischer commented
/cc @hmaarrfk

2020-10-22 21:53 UTC, hmaarrfk commented
Does glib not have a run exports? I guess we should work to add that

2020-10-23 00:50 UTC, pkgw commented
This issue is due to the recent glib/libglib separation. Now the full `glib` package is effectively the "dev" version of the package, and required if you want to do "dev"-like things with Harfbuzz, like use its pkg-config file.

The motivation for the split was that the full `glib` package depends on Python, and we don't want to drag in this dependency for libraries that don't need the glib developer tools. For this reason, I think it would be good to avoid making `glib` a runtime dependency of Harfbuzz. But, as things currently stand, the alternative is that packages that develop against harfbuzz have to "know" to depend on `glib` too to get the full set of necessary development files. I recently made just such a change to `tectonic`.

This is all very relevant to https://github.com/conda-forge/cfep/pull/39 !

2020-10-27 12:38 UTC, pkgw commented
@Tobias-Fischer @hmaarrfk How would you feel about adding glib to the host deps but not run deps? It will mean that people building against harfbuzz will have to know to add glib as their own host dependency, but because the full glib run dep pulls in python, I think that is the less-bad way to go in this case.

2020-10-27 19:23 UTC, Tobias-Fischer commented
That sounds sensible to me, but better wait for @hmaarrfk's opinion as I don't have enough knowledge of conda to have an expert opinion.

2020-10-27 22:01 UTC, hmaarrfk commented on recipe/meta.yaml
> +    - glib
```suggestion
    - libglib
```

2020-10-27 22:01 UTC, hmaarrfk commented on recipe/meta.yaml
> +    - glib
A libglib package that doesn't rely on python.
https://github.com/conda-forge/glib-feedstock/blob/master/recipe/meta.yaml#L97

2020-10-27 22:02 UTC, hmaarrfk commented
Sorry, tey are a little harder to find, but a subpackage libglib exists to solve the problem of relying on "full glib" for python.
https://github.com/conda-forge/glib-feedstock/blob/master/recipe/meta.yaml#L97

2020-10-27 23:37 UTC, hmaarrfk commented
@conda-forge-admin please rerender

2020-10-28 01:26 UTC, hmaarrfk commented
Looking great

2020-10-28 01:42 UTC, pkgw approved these changes
I don't think this will fix the `opencv` build issue in and of itself, because the `libglib` package doesn't contain the pkg-config definition file. But I think this is a fine change to make.

2020-10-28 12:19 UTC, hmaarrfk commented
@pkgw that seems odd. To mee, the `pkg-config` file is definitely a build requirement file. Maybe we should make the PR in that feedstock?

2020-10-28 12:28 UTC, hmaarrfk commented
if opencv needs pkg-config from glib, then it definitely depends on glib, in addition to harfbuzz

2020-10-28 13:05 UTC, xhochy requested changes
This should make no difference and if it does, there is an issue in conda-build.

2020-10-28 13:05 UTC, xhochy commented on recipe/meta.yaml
> +    - libglib
This is redundant. `glib` has a `run_exports` for `libglib` and thus this should be added automatically by conda-build.

2020-10-28 13:37 UTC, hmaarrfk commented
Thanks xhochy!

2022-03-12 22:17 UTC, closed without merging